### ISSUE TITLE
ds4vita problem

### ISSUE THREAD

**Issue by marcoc02** [xerpi/ds4vita#1]
Nice job with the ds4vita plug in it is very good… but it conflict with games with mai-moe folder, they don’t start anymore and when I remove the plugin they restart again.

**Comment by xerpi** [comment]
What does "mai-moe folder" mean exactly?

**Comment by parkerlreed** [comment]
I think it's a dump from Maitool or whatever that Vitamin alternative is called.

**Comment by marcoc02** [comment]
@xerpi When I install the plugin I can't play games in MaiDumpTool format anymore but when I remove it yes

**Comment by xerpi** [comment]
@marcoc02 a few people have reported that, so I'll try to fix it as soon as possible.

**Comment by xerpi** [comment]
I've found out the issue. It was that Mai load *ALL* the plugins inside ux0:/plugins when it should really _not_ do that. Just place the plugin in another folder (ux0:/tai for example).
