### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by wolfarine** [xerpi/ds4vita#16]
Hello, i'm a vita dev newbie .  I find that the ds4vita is a very cool plugin. 
A ds4 can connect to a vita automaticly and take over the physical joysticks and butttons Magicly.
So i tried to lookup into the code to learn the taihen func hook...
And it is the first time for me to run CMAKE to gen the makefile.
But the CMAKE told me:
`CMake Error at CMakeLists.txt:19 (if):
if given arguments:
"(" "EQUAL" "1"  ")"
Unknown arguments specified`
I have no idea how to modify the allowing code inside the cmakelists.txt
'if (${RELEASE} EQUAL 1)
	add_definitions(-DRELEASE)
endif()'
So i just delette the if(...) and endif(). Now i got the makefile to make the .skprx
But there is still some problem when making the project:
'...missing -lSceThreadmgrForKernel_stub...'
After looking into the lib dir, i didn't find the relevant .a lib file.
So i just delette   -lSceThreadmgrForKernel_stub inside the cmaklists.txt then regen the makefile.
Eventually, i got the compiling passed. And get the .skprx file which is running ok on my taihen vita.
But i still don't know the right way to solve these problem.

**Comment by parkerlreed** [comment]
...

````
cmake -DRELEASE=1 ..
````

**Comment by xerpi** [comment]
Fixed with 529635eaa5ac7cb87d377213a6e4d1b55541b3af.
