### ISSUE TITLE
cannot connect

### ISSUE THREAD

**Issue by senamegamilk** [xerpi/ds4vita#2]
I'm trying to connect my DS4 to vita and following this guide.

Enable the plugin:

  Add ds4vita.skprx to taiHEN's config.txt (*KERNEL section), example:
    *KERNEL
    ux0:plugins/ds4vita.skprx
    You need to refresh the config.txt by rebooting or through VitaShell.

Using it for the first time (pairing the controller):

    Go to Setting -> Devices -> Bluetooth Devices
    Press SHARE+PS on the DS4 for about 3 seconds, until the lightbar blinks
    The DS4 will then connect and be paired (don't press over it when it appears)

But my DS4 isn't pairing the Vita see's the controller but doesn't pair with it automatically and if i press the controller on devices screen it says "Could not find a profile supported by this system"

I've tried re-writing the code as
ux0:plugins/ds4vita.yml
and it still doesn't work I don't know what I'm doing wrong but i feel like this isn't explained very well at all.

**Comment by senamegamilk** [comment]
Maybe some kind of visual guide properly detailing and showing how this is done cause I'm at a loss. Ive tried everything i could with the old files and new files, Henkaku/Taihenkaku/Taihen offline, switchkaku

**Comment by xerpi** [comment]
After enabling the plugin (adding ux0:plugins/ds4vita.skprx to ux0:tai/config.txt), reboot your Vita.

**Comment by senamegamilk** [comment]
I did this already my config.txt looks like this 

# You must reboot for changes to take place
*KERNEL
ux0:plugins/ds4vite.skprx
ux0:pspemu/adrenaline/adrenaline.skprx

**Comment by xerpi** [comment]
I see a typo there: "ds4vite"

**Comment by senamegamilk** [comment]
What typo?
ds4vite thats what i typed

**Comment by senamegamilk** [comment]
Im posting my Config file to see if you can see what im doing wrong.. its still not working I placed all the files in plugins and this is my config file. I tried both .yml and skprx the vita sees the ds4 but never connects it just blinks then turns off.

# You must reboot for changes to take place.
*KERNEL
ux0:plugins/ds4vita.yml
ux0:plugins/ds4vita.skprx
ux0:pspemu/adrenaline/adrenaline.skprx
# henkaku.skprx is hard-coded to load and is not listed here
*main
# main is a special titleid for SceShell
ux0:app/MLCL00001/henkaku.suprx
*NPXS10015
# this is for modifying the version string
ux0:app/MLCL00001/henkaku.suprx
*NPUG80061
vs0:sys/external/libpgf.suprx
ux0:pspemu/adrenaline/adrenaline.suprx

**Comment by xerpi** [comment]
Uhm.. are all of these big bold text also present in the config file?

**Comment by senamegamilk** [comment]
Thats what ive been doing but it never connects.  Also there is no Skprx file in that folder when i downloaded it was it suppose to be?

**Comment by xerpi** [comment]
Cool, so I guess I can close this issue.
