### ISSUE TITLE
System goes into standby when playing Vita games + RetroArch compatibility issues

### ISSUE THREAD

**Issue by Crezdonn** [xerpi/ds4vita#3]
The backlight turns off after a minute or so like usual, and the system will enter sleep mode after the amount of time you set in settings (max 30 mins). This doesn't happen in adrenaline. It's like the button presses from the controller aren't registering on the main system as button presses, but you can still play the games normally.

When I'm using RetroArch I can't use the controller at all. I tried multiple reboots + reloading beta.henkaku.xyz, can't seem to get it working.

**Comment by parkerlreed** [comment]
RetroArch handles buttons differently and the timeout can be changed with the Registry Editor for Vita.

**Comment by Crezdonn** [comment]
I'm unfamiliar with the registry editor, so looks like I'll have to do some researching. Thanks.

**Comment by parkerlreed** [comment]
Here you go https://gbatemp.net/threads/disable-auto-dim-on-ps-vita-with-registry-editor-and-henkaku.441890/

**Comment by Crezdonn** [comment]
Thank you!

**Comment by parkerlreed** [comment]
Well latest beta fixes the suspend issue! Thanks @xerpi!

**Comment by xerpi** [comment]
Yup, fixed by 61eb55828ffb3af30c4b1ac8d4773fa4726cded1.
