### ISSUE TITLE
ds4vita setup issue.

### ISSUE THREAD

**Issue by dickcheney** [xerpi/ds4vita#33]
Looking for some help setting up DS4Vita, I have placed the SKPRX and config (as well as configuring the config see below) but it comes up with the error "could not find a profile supported by this system". I have reloaded the config as well as rebooting to no avail. Sometimes when trying two bluetooth devices show up (1 headset with no label and 1 wireless controller (labeled).

Config

This file is used as an alternative if ux0:tai/config.txt is not found.

For users plugins, you must refresh taiHEN from HENkaku Settings for changes to take place.
For kernel plugins, you must reboot for changes to take place.

*KERNEL
ux0:app/PSPEMUCFW/sce_module/adrenaline_kernel.skprx
ux0:tai/ds4vita.skprx

henkaku.skprx is hard-coded to load and is not listed here
*main

main is a special titleid for SceShell
ur0:tai/henkaku.suprx
*NPXS10015

this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016

this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx

titleid for your game (this one is for Root//Letter for example)
*ALL
ux0:tai/oclockvita.suprx
ux0:tai/trophax0.2.suprx

**Comment by dickcheney** [comment]
Edited comment - Removed pound symbol for easier reading.

**Comment by xerpi** [comment]
Are you pressing SHARE+PS on the DS4 for about 3-4 seconds?

**Comment by dickcheney** [comment]
Yes,  it starts blinking quickly shows up on the devices list but the error pops up when i try to connect.

**Comment by xerpi** [comment]
You don't have to press it when it appears on the Vita, it should automatically connect.

**Comment by dickcheney** [comment]
thats the problem its not completing the pairing process.

Images - https://imgur.com/a/ExE7i

**Comment by dickcheney** [comment]
Couldn't figure it out, reinstalled enso and ds4vita working fine now.

Please close 

Thanks

**Comment by eiiiiix** [comment]
I was just having the same issue
Fixed it by changing bootconfig to load from ur0:
Really inconveinent now because i prefeer loading from ux0: and now i have to reinstall firmware when i screw up and my custom gamma has to be manually loaded but now i can use wireless controlers again
