### ISSUE TITLE
streamylined fix xd

### ISSUE THREAD

**Issue by miku-chan69** [xerpi/ds4vita#36]
Hii~~

I fixie wixied the JSON-api fucksy wucksie!!! xpp

I repwaced the `Protoypes.func` wiff a more ~ streamylined ~ kawaii
`Pwototypiee.funkywunks` object that make the JS go sooper dooper fast!!
xD *starts twerking*

Can u pwease merge my pwull wequest senpai?!! UwU

**Comment by parkerlreed** [comment]
I think you posted to the wrong project....

**Comment by xerpi** [comment]
I bet it's just a shitty bot.
