### ISSUE TITLE
Left analog doesn't fully tilt in some directions.

### ISSUE THREAD

**Issue by devanteweary** [xerpi/ds4vita#47]
I was playing Persona 4 Golden and noticed when I press down or left, the character walks instead of runs. The other directions are fine.

I tried Earth Defense Force and it seemed to work normally there.

**Comment by devanteweary** [comment]
Forgot to mention that I'm on 3.65 Enso.

**Comment by xerpi** [comment]
Can you check this out? https://github.com/xerpi/ds4vita/issues/43#issuecomment-431850355

**Comment by devanteweary** [comment]
Yes, that version fixed it! Thanks so much!

**Comment by Girotin** [comment]
Should close this one :p
