### ISSUE TITLE
#43 Left analog stick issue

### ISSUE THREAD

**Issue by dkrmdi** [xerpi/ds4vita#51]
I tired the version you uploaded on google drive, but the controls were quite compromised.

The lastest plugin handled the motion sensor better. I am playing gravity rush and digimon cyber sleuth.

I hope you can improve this plugin. Thank you.

**Comment by parkerlreed** [comment]
You can just comment on #43. No need for the separate issue.

**Comment by dkrmdi** [comment]
My bad. I'll close this issue.
