### ISSUE TITLE
Something needs to be made

### ISSUE THREAD

**Issue by Girotin** [xerpi/ds4vita#54]
The #43, and the #39  threads, talks about this already, but it's obvious that a new release with options, or an fixed deadzone version need to be made for a better experience with the DualShocks. The latest release works almost perfectly; the only problem it's the deadzone in the sticks; both them need to be almost fully pulled over for the Vita start detecting the moves, and even fully pulled, some directions still don't reach their max value;
Ex:
Pulling the analog fully to right, reaches around 240/239
It should be getting 255 static,

Seems like isn't that important, but this little difference can make your character to stop runningg in a lot of 3D games.

Some alternative releases were send for use here in the issues thread, and Reddit, by the own Xerpi, that kinda fix this problem:
Now pulling the stick to the right, reaches 255 and keeps static, but the diagonals are very unstable, and even so;

We still have the issue of needing to almost fully pull the stick to it works, the L2 and R2 buttons kinda don't work in the same way anymore, and almost like if it wasn't bad, it gets even worse, since the DSMotion plugin glitches completely with those versions.

It makes a complete mess with some stuff, but at least the analogs received an improvement, and kinda can be used.

That being said, it's clear that something needs to be made. A new release with options to change the deadzone by ourselves, or a release with a decent deadzone, or if there's literally no time to work on this anymore, a post in the Twitter, or anything, so that we can stop believing this will receive any fix. Otherwise we have to keep changing the plugins everytime if we want our character to runn, or if we want to use the motion sensors. I even tried to use both them together, but it works for some minutes, and then all the buttons glitch completely after some time 

Seriously, the latest release for this it's from 2017, we're almost in 2020, and not even an alpha test was officialy released from that day (at least not here in GitHub).

This makes games like Uncharted unplayable in certain areas, and Gravity Rush that uses motion sensors almost as it's first base, become unplayable.

I think that's the only problem that needs some urgent fix, DSMotion works great in the latest version, buttons and stuff also work great too, L2, R2, R3, and L3 still aren't a clear use (for me they're working nicely), but they don't are as needed than working analog sticks.

I know that Xerpi doesn't have much time to work on this, and don't even receive any money back, but if possible, fixing this would be an excellent add on for the Vita. Don't know how much time this needs to be fixed too, but dude, this is a plugin for the community, almost all of the projects doesn't receive any money, or help on it, whenever this gets fixed (if it gets fixed), it will be highly appreciated. 

For now, i'll be avoiding all types of games that need motion sensors when using it.

**Comment by Girotin** [comment]
The sticks on the Vita are very small, so it is extremely sensitive, the DS4 should have that same sensitivity too, so it not only will be loyal to the original Vita experience, but will avoid glitches like your character to stop running.

Some beta releases would be extremely appreaciated, so that not only we'll be able to keep testing all the possibilities, until a great final release, but also we'll know that's still a WIP. The latest release have great working motion sensors, and the previous version says that some changes were made in the deadzone, we don't expect any problems when installing it, but that isn't what we really get.

**Comment by djsawicko** [comment]
Make a version of ds4vita that uses l2 as l trigger an r2 as r trigger! (This is a critical feuture!) For example in shooting games (like Unit 13) I always default to the analog triggers! Plus the sensitivity feels way off on the analog sticks! Also it'd be great to be able to change the color of the lightbar, or at least make it a solid blue!
