### ISSUE TITLE
[Feature Request]Turning off ds4 light bar.

### ISSUE THREAD

**Issue by kemalsanli** [xerpi/ds4vita#56]
First of all, Thanks ^^

I have a vita 1004, with the lastest update i have a very very good experience with your plugins, thank you for contributions to community.

While playing games with my ds4 controller on pc i can remotely turn off ds4 light bar with ds4windows, if you can make a feature like this im pretty sure ds4 controller battery will last longer and people love it.

**Comment by xerpi** [comment]
I think you might be able to change the RGB color here: https://github.com/xerpi/ds4vita/blob/master/main.c#L181

**Comment by kemalsanli** [comment]
Thank you for your answer, i didnt compile any vita plugin before, i can try it now thanks for your hard work.

But for newbies like me maybe you can make another package for light off like udcd-uvc-screen-off one. 

Hope you have a nice day ^^

**Comment by xerpi** [comment]
You'll need vitasdk to compile: https://vitasdk.org/

**Comment by kemalsanli** [comment]
Thank you for your kindly answer.
