### ISSUE TITLE
L1/R1 being mapped to L2/R2 in certain games 

### ISSUE THREAD

**Issue by TheIronUniverse** [xerpi/ds4vita#58]
Hello!

In release1.2 of DS4Vita, the plugin always mapped the Vita's L and R buttons to SCE_CTRL_L1 and SCE_CTRL_R1, as expected. This was consistent in every game, including system apps. However in the expiremental-hooks release of DS4Vita, peekbufferpositive and peekbufferpositiveext2 map the Vita's L button and R button to different values for no notable reason. On standard func the Vita L button and R button are mapped to the equivalent of DS4 L2 and R2. In ext2 they're mapped to L1 and R1, as they should be.

any idea how to fix this? it wasn't there in the previous release and it would be a big help toward the VitaDock project. thanks!

a good way to test this is to switch between scenes in LiveArea with the L and R buttons, when you have an app open for example.

*NOTED GAMES THAT ARE AFFECTED BY THIS
• Skullgirls: 2nd Encore
• RetroArch
• PS4Link

**Comment by TheIronUniverse** [comment]
lemme make a correction, do correct me if I'm wrong, I believe sceCtrlPeekBufferPositiveExt2 is what's causing the Vita L/R buttons to be mapped to L2/R2, not sceCtrlPeekBufferPositive.

**Comment by xerpi** [comment]
I think that's correct.

**Comment by TheIronUniverse** [comment]
do you think you can take a look at it? @xerpi any idea why it's doing that?

**Comment by TheIronUniverse** [comment]
I think a good fix would be to patch peekBufferPositiveExt2 to have the same bindings as peekBufferPositive. it's definitely possible.

**Comment by TheIronUniverse** [comment]
nevermind, I started using remaPSV, and now I can just remap it myself on a per game basis.
