### ISSUE TITLE
Analog stick moves by itself

### ISSUE THREAD

**Issue by xym814** [xerpi/ds4vita#6]
On the Hatsune Miku Project Diva X customize menu(Change costumes and accessories),the L analog will start to go left automatically , meanwhile the R analog will start to go upwards automatically.

**Comment by Miguel5tuxD** [comment]
I have the same problem but with Diva F2 , it's like this your error ? 
[video_error.zip](https://github.com/xerpi/ds4vita/files/680143/video_error.zip)

**Comment by Miguel5tuxD** [comment]
Jajajaja I check my Diva X and now I know what he was talking about , check this , please Someone fix it please
[video_error2.zip](https://github.com/xerpi/ds4vita/files/680145/video_error2.zip)

**Comment by xerpi** [comment]
The latest version fixed this problem (I think).
