### ISSUE TITLE
Problem with sticks 

### ISSUE THREAD

**Issue by Miguel5tuxD** [xerpi/ds4vita#7]
Hi That such developer, thanks for this great puglin that you have developed is excellent, I wanted to report an error that I found, in the game Hatsune Miku Project Diva F2, since Beta 2 there is a problem with the puglin, the character moves left without Touch the sticks, this did not happen in version 1.4, if you could solve it please
Thank You if you can fix it , here is a video showing the error Thank You
I prove this with  2.1.1 , so for me the more stable version is 1.4 in that doesn't happen it xD , thanks for reading 
[video_error.zip](https://github.com/xerpi/ds4vita/files/680142/video_error.zip)

**Comment by Miguel5tuxD** [comment]
let me add another problem that it's the same of the user Issue #6 @xym814 , @xerpi please help us to fix it  , in that Issue I comment the other problem please try to fix it Thank You

**Comment by xerpi** [comment]
Thanks for the report, I'll try to fix it asap.

**Comment by xerpi** [comment]
Are you using Mai?

**Comment by Miguel5tuxD** [comment]
@xerpi You are the best thank you very much the last version fix it , I don't know what did you do , but thank you very much :1st_place_medal:  :D  👍 💯
