### ISSUE TITLE
reVita crashes when using ds34vita

### ISSUE THREAD

**Issue by MaixGit** [xerpi/ds4vita#74]
Without the plugin installed reVita works perfectly fine, but while ds34vita is installed, I can open the menu but when I try to exit the menu it crashes, it also instantly crashes when I try to open it in safe mode

**Comment by xerpi** [comment]
Try with this plugin: https://github.com/Hydr8gon/VitaControl

**Comment by MaixGit** [comment]
The issue was fixed after a second clean install of both plugins:
https://github.com/MERLev/reVita/issues/26
